/**
 * reportService.js – Generates the downloadable report files (JSON + HTML).
 * Single Responsibility: only handles report file content generation.
 */

const LEVEL_ORDER = { Beginner: 1, Intermediate: 2, Advanced: 3, Expert: 4 };

/**
 * Build the structured JSON report content.
 * @param {{ name: string, level: string }[]} skills
 * @returns {string} Formatted JSON string.
 */
function generateJson(skills) {
  return JSON.stringify({ skills }, null, 2);
}

/**
 * Build a standalone HTML file with an inline SVG bar chart of skills.
 * The file must open correctly without a running server (no external resources).
 * @param {{ name: string, level: string }[]} skills
 * @returns {string} Full HTML string.
 */
function generateHtml(skills) {
  if (skills.length === 0) {
    return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>Skills Report</title>
  <style>
    body { font-family: Arial, sans-serif; padding: 2rem; background: #f9f9f9; color: #333; }
    h1 { color: #444; }
    .empty { color: #888; margin-top: 2rem; font-size: 1.1rem; }
  </style>
</head>
<body>
  <h1>Skills Report</h1>
  <p class="empty">⚠️ No skills available.</p>
</body>
</html>`;
  }

  // Chart dimensions
  const BAR_HEIGHT = 28;
  const BAR_GAP = 10;
  const LABEL_WIDTH = 180;
  const MAX_BAR_WIDTH = 320;
  const MAX_LEVEL = 4;
  const PADDING = { top: 20, bottom: 20, left: 10, right: 30 };

  const chartHeight =
    PADDING.top + skills.length * (BAR_HEIGHT + BAR_GAP) - BAR_GAP + PADDING.bottom;
  const chartWidth = LABEL_WIDTH + MAX_BAR_WIDTH + PADDING.left + PADDING.right;

  const LEVEL_COLORS = {
    Beginner: '#a8d5ba',
    Intermediate: '#5ba4cf',
    Advanced: '#f0a500',
    Expert: '#e05c5c',
  };

  const bars = skills
    .map((skill, i) => {
      const levelValue = LEVEL_ORDER[skill.level] || 2;
      const barWidth = (levelValue / MAX_LEVEL) * MAX_BAR_WIDTH;
      const y = PADDING.top + i * (BAR_HEIGHT + BAR_GAP);
      const color = LEVEL_COLORS[skill.level] || '#5ba4cf';
      const labelX = PADDING.left + LABEL_WIDTH - 8;
      const barX = PADDING.left + LABEL_WIDTH;

      return `
    <g>
      <text x="${labelX}" y="${y + BAR_HEIGHT / 2 + 5}" text-anchor="end"
            font-family="Arial, sans-serif" font-size="13" fill="#333">${_escapeXml(skill.name)}</text>
      <rect x="${barX}" y="${y}" width="${barWidth.toFixed(1)}" height="${BAR_HEIGHT}"
            rx="4" fill="${color}" />
      <text x="${(barX + barWidth + 6).toFixed(1)}" y="${y + BAR_HEIGHT / 2 + 5}"
            font-family="Arial, sans-serif" font-size="11" fill="#666">${_escapeXml(skill.level)}</text>
    </g>`;
    })
    .join('');

  const svg = `<svg xmlns="http://www.w3.org/2000/svg"
     width="${chartWidth}" height="${chartHeight}"
     role="img" aria-label="Skills chart">
  <title>Skills Chart</title>
  ${bars}
</svg>`;

  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>Skills Report</title>
  <style>
    body { font-family: Arial, sans-serif; padding: 2rem; background: #f9f9f9; color: #333; }
    h1 { color: #444; margin-bottom: 0.25rem; }
    .subtitle { color: #888; margin-bottom: 1.5rem; font-size: 0.95rem; }
    .chart-container { background: #fff; border: 1px solid #ddd; border-radius: 8px; padding: 1.5rem; display: inline-block; }
    .legend { margin-top: 1rem; display: flex; gap: 1rem; flex-wrap: wrap; font-size: 0.85rem; }
    .legend-item { display: flex; align-items: center; gap: 0.4rem; }
    .legend-color { width: 14px; height: 14px; border-radius: 3px; }
  </style>
</head>
<body>
  <h1>Skills Report</h1>
  <p class="subtitle">Generated by Skills Extractor &mdash; ${skills.length} skill(s) found</p>
  <div class="chart-container">
    ${svg}
    <div class="legend">
      <div class="legend-item"><div class="legend-color" style="background:#a8d5ba"></div>Beginner</div>
      <div class="legend-item"><div class="legend-color" style="background:#5ba4cf"></div>Intermediate</div>
      <div class="legend-item"><div class="legend-color" style="background:#f0a500"></div>Advanced</div>
      <div class="legend-item"><div class="legend-color" style="background:#e05c5c"></div>Expert</div>
    </div>
  </div>
</body>
</html>`;
}

/**
 * Escape special XML/HTML characters to prevent markup injection in SVG.
 * @param {string} str
 * @returns {string}
 */
function _escapeXml(str) {
  return String(str)
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#39;');
}

module.exports = { generateJson, generateHtml };
