/**
 * reportService.js – Generates the downloadable report files (JSON + HTML).
 * Single Responsibility: only handles report file content generation.
 * HTML structure lives in report.html; styles live in report.css.
 */

const fs = require('fs');
const path = require('path');

const TEMPLATE_PATH = path.join(__dirname, 'report.html');
const CSS_PATH = path.join(__dirname, 'report.css');

const LEVEL_ORDER = { Beginner: 1, Intermediate: 2, Advanced: 3, Expert: 4 };

/**
 * Build the structured JSON report content.
 * @param {{ name: string, level: string }[]} skills
 * @returns {string} Formatted JSON string.
 */
function generateJson(skills) {
  return JSON.stringify({ skills }, null, 2);
}

/**
 * Build a standalone HTML file with an inline SVG bar chart of skills.
 * The file must open correctly without a running server (no external resources).
 * @param {{ name: string, level: string }[]} skills
 * @returns {string} Full HTML string.
 */
function generateHtml(skills) {
  const styles = fs.readFileSync(CSS_PATH, 'utf8');
  const template = fs.readFileSync(TEMPLATE_PATH, 'utf8');

  const content =
    skills.length === 0 ? _emptyContent() : _chartContent(skills);

  return template
    .replace('{{STYLES}}', styles)
    .replace('{{CONTENT}}', content);
}

/**
 * Return the HTML content block for the empty-skills case.
 * @returns {string}
 */
function _emptyContent() {
  return '<p class="empty">⚠️ No skills available.</p>';
}

/**
 * Return the HTML content block containing the SVG chart and legend.
 * @param {{ name: string, level: string }[]} skills
 * @returns {string}
 */
function _chartContent(skills) {
  const LEVEL_COLORS = {
    Beginner: '#a8d5ba',
    Intermediate: '#5ba4cf',
    Advanced: '#f0a500',
    Expert: '#e05c5c',
  };

  const BAR_HEIGHT = 28;
  const BAR_GAP = 10;
  const LABEL_WIDTH = 180;
  const MAX_BAR_WIDTH = 320;
  const MAX_LEVEL = 4;
  const PADDING = { top: 20, bottom: 20, left: 10, right: 30 };

  const chartHeight =
    PADDING.top + skills.length * (BAR_HEIGHT + BAR_GAP) - BAR_GAP + PADDING.bottom;
  const chartWidth = LABEL_WIDTH + MAX_BAR_WIDTH + PADDING.left + PADDING.right;

  const bars = skills
    .map((skill, i) => {
      const levelValue = LEVEL_ORDER[skill.level] || 2;
      const barWidth = (levelValue / MAX_LEVEL) * MAX_BAR_WIDTH;
      const y = PADDING.top + i * (BAR_HEIGHT + BAR_GAP);
      const color = LEVEL_COLORS[skill.level] || '#5ba4cf';
      const labelX = PADDING.left + LABEL_WIDTH - 8;
      const barX = PADDING.left + LABEL_WIDTH;

      return `
    <g>
      <text x="${labelX}" y="${y + BAR_HEIGHT / 2 + 5}" text-anchor="end"
            font-family="Arial, sans-serif" font-size="13" fill="#333">${_escapeXml(skill.name)}</text>
      <rect x="${barX}" y="${y}" width="${barWidth.toFixed(1)}" height="${BAR_HEIGHT}"
            rx="4" fill="${color}" />
      <text x="${(barX + barWidth + 6).toFixed(1)}" y="${y + BAR_HEIGHT / 2 + 5}"
            font-family="Arial, sans-serif" font-size="11" fill="#666">${_escapeXml(skill.level)}</text>
    </g>`;
    })
    .join('');

  const svg = `<svg xmlns="http://www.w3.org/2000/svg"
     width="${chartWidth}" height="${chartHeight}"
     role="img" aria-label="Skills chart">
  <title>Skills Chart</title>
  ${bars}
</svg>`;

  return `<p class="subtitle">Generated by Skills Extractor &mdash; ${skills.length} skill(s) found</p>
  <div class="chart-container">
    ${svg}
    <div class="legend">
      <div class="legend-item"><div class="legend-color" style="background:#a8d5ba"></div>Beginner</div>
      <div class="legend-item"><div class="legend-color" style="background:#5ba4cf"></div>Intermediate</div>
      <div class="legend-item"><div class="legend-color" style="background:#f0a500"></div>Advanced</div>
      <div class="legend-item"><div class="legend-color" style="background:#e05c5c"></div>Expert</div>
    </div>
  </div>`;
}

/**
 * Escape special XML/HTML characters to prevent markup injection in SVG.
 * @param {string} str
 * @returns {string}
 */
function _escapeXml(str) {
  return String(str)
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#39;');
}

module.exports = { generateJson, generateHtml };

